### PR TITLE
[6.x] Set default faker_locale

### PR DESCRIPTION
**Pull request by BlackLanzer**
Hello

this PR is for https://github.com/orchestral/testbench/discussions/292.

I made it for 6.x, but I think it should work from 4.x if needed.

Do you want me to make a PR for all the newer versions?

### CODE REVIEW

**Comment by crynobone** [comment]
I on vacation at the moment but I believe this can already be archived by using `WithConfig` attribute.

**Comment by BlackLanzer** [comment]
I'm not sure why, but WithConfig does not work.  
I think it's the same reason they talk about in the issue.  
Also, if you need to support php < 8.0, attributes with constructor do not work.

I tried this, but it does not pass.

```php
#[WithConfig("app.faker_local", "it_IT")]
class FakerLocaleTest extends TestCase
{
 use WithFaker;
 /** @test */   
 public function it_can_override_faker_locale()
    {
        $providerNames = array_map(function ($p) {
            return get_class($p);
        }, $this->faker()->getProviders());

        $this->assertContains('Faker\Provider\it_IT\Person', $providerNames);
    }
}

**Comment by crynobone** [comment]
The suggestion was  originally made on 2020, I would rather work on ensuring WithConfig attribute works for faker instead of adding new method.

**Comment by BlackLanzer** [comment]
Lol I made a typo. WithConfig works.

Sorry for wasting your time.

**Pull request closed without merging**
