### PR TITLE
Improves PHPUnit memory leaks

### PR DESCRIPTION
**Pull request by crynobone**
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Comment by jasonvarga** [comment]
@crynobone FYI we have our Windows test suite failing now that it's running 7.8.0.

Basically every test fails with this sort of error:

```
1) Tests\API\APITest::not_found_responses_are_formatted_with_json
Error: Access to undeclared static property Tests\API\APITest::$latestResponse

D:\a\cms\cms\vendor\orchestra\testbench-core\src\TestCase.php:50
D:\a\cms\cms\tests\TestCase.php:18
```

Here's a run: https://github.com/statamic/cms/actions/runs/3146066349/jobs/5114089006

**Comment by ash-phoenix-wombat** [comment]
The issue highlighted by @jasonvarga is also affecting our test suite.

**Comment by crynobone** [comment]
Don't use `^` on your build pipeline and that should solve the issue.

**Comment by jasonvarga** [comment]
If your `composer require` step in your action workflow was doing `composer require laravel/framework:^8.0` for example, you should change it to `composer require illuminate/contracts:8.*`

**Pull request merged**
