### PR TITLE
Replicate changes made in laravel #29267

### PR DESCRIPTION
**Pull request by paulhenri-l**
Following on #25

### CODE REVIEW

**Comment by crynobone** [comment]
The PR can be made to `3.8` branch

**Comment by paulhenri-l** [comment]
Yea I wasn't sure about the branch 😉

**Comment by crynobone** [comment]
Nevermind, I'll merge this first and cherry-pick the commit to 3.8

**Comment by paulhenri-l** [comment]
Good idea :)

**Pull request merged**
