### PR TITLE
[9.x] Reset refresh database state between tests

### PR DESCRIPTION
**Pull request by crynobone**

### CODE REVIEW

**Comment by brunogaspar** [comment]
@crynobone Hello 👋 

Sadly, this has caused a regression, at least on my end. I'm also aware this logic was moved to the `InteractsWithTestCase` trait.

I've been using the `RefreshDatabase` trait for quite some time, even after Laravel 11 upgrade, but after this change, the trait still works, but the migrations are executed before each test, which seems unwanted (at least from my point of view), which in turn makes the tests slow as the more migrations you have, the slow it will be 😞 

Do i need to change something on my end?

Thank you!!

**Comment by crynobone** [comment]
This PR only available for Testbench Core 6 and was done for forward compatibility up until 9.

**Comment by crynobone** [comment]
See https://github.com/orchestral/testbench-core/commit/89305293c60c0f828fc4f396c16d9d65184b590c

**Comment by crynobone** [comment]
Oh yeah, my mistake. There are two `RefreshDatabase` usages in Testbench. 

1. Consistent migrations per test case.
2. Ad-hoc migrations between tests in test cases.

While Laravel application mostly uses structure 1, Package developers have been known to use structure 2, which led to the above changes. We will need to rethink this

**Comment by brunogaspar** [comment]
No problem.

I'm pretty much on structure 1 but on a package, testing against a MySQL database not a in memory one (i know it's a bit unconventional).

I have for now implemented a workaround so it does not use the `RefreshDatabaseState::$migrated`

Let me know if there's anything i can help to address it.

**Comment by crynobone** [comment]
> I'm pretty much on structure 1 but on a package, testing against a MySQL database not a in memory one (i know it's a bit unconventional).

`RefreshDatabase` in Laravel 11 for `:in-memory:` was changed to work similarly to a persistent database which prompted these changes (tests will break with structure 2).

**Comment by crynobone** [comment]
@brunogaspar can you test the latest patch release and see if that fixed your issue.

**Comment by brunogaspar** [comment]
@crynobone Yes, that seemed to have fixed it.

Thank you!!

**Pull request merged**
